# 构建超图的config文件
graph_constructor:
  dataset: BRCA
  task: "cancer typing"
  data_root: "/mnt/Drive2/aweers/tcga-brca-20/patches/"
  # hovernet_data_root: "./data/hovernet_json"
  h5_path: "/mnt/Drive2/aweers/tcga-brca-20/patches/patches/"
  wsi_path: '/mnt/Drive2/aweers/tcga-brca-20/svs_files/'
  out_dir: "/mnt/Drive2/aweers/tcga-brca-20/out-folder/"
  # normal_graph_path: "/home/dataset2/hmh_data/my_secpro_data/het_graph/new_BRCA/except_topo/"
  normal_graph_path: "" 
  new_graph_type: "None" #optional[except_topo, except_mix, None]
  encoder_name: 'ctrans'
  patch_size: 224
  feature_dim: 1024
  cell_radius: 10
  tissue_radius: 7
  level: 2
  n_channel: 3
  n_node_type: 6
  verbose: 0
  encoder_patch_size: 224

encoder_config:
  encoder_type: "ctrans" # optional [kimianet, ctrans]
  kimianet_model_path: '/home/hmh/weights/KimiaNetPyTorchWeights.pth'
  ctrans_model_path: '/home/home/weers_johannes/git/H2GT/pretrained_ctranspath.pt'
  batch_size: 64

hovernet_config:
  nr_types: 6
  mode: fast
  hovernet_model_path: '/home/home/weers_johannes/git/H2GT/hover_pannuke.tar'
  type_info_path: 'type_info.json'
  batch_size: 64
  hover_patch_size: 256
